Add a tweet for metric_template video
operate-first/operate-first-twitter pull request #23
Opened 2021-06-28 15:09 UTC by Shreyanand

This PR closes https://github.com/aicoe-aiops/ocp-ci-analysis/issues/296 by adding a tweet to promote the metric template Youtube video.

2021-06-28 15:09 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **tumido** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @tumido` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first-twitter).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first-twitter/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["tumido"]} -->

2021-06-29 18:50 UTC, harshad16 approved these changes
/lgtm
thanks :100:

2021-06-29 18:50 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/operate-first-twitter/pull/23#pullrequestreview-695390970" title="LGTM">harshad16</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **tumido** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @tumido` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first-twitter).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first-twitter/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["tumido"]} -->

2021-06-30 20:44 UTC, chauhankaranraj requested changes
Small suggestion to make the tweet clearer, lmk what you think :)

2021-06-30 20:44 UTC, chauhankaranraj commented on tweets/2021-06/metric_template.tweet
> +Interested in monitoring and improving your CI process? Be sure to checkout https://youtu.be/ouxtHH2vOHg to write notebooks for Key Performance Indicators using #AI4CI metric template.
```suggestion
Interested in monitoring and improving your CI process? Check out https://youtu.be/ouxtHH2vOHg to learn how to write Jupyter notebooks using the #AI4CI metric template to calculate Key Performance Indicators for CI.
```

2021-07-02 14:05 UTC, sesheta commented
New changes are detected. LGTM label has been removed.

2021-07-02 14:25 UTC, chauhankaranraj commented
/lgtm :rocket:

2021-07-02 14:49 UTC, oindrillac approved these changes
/lgtm 🐦 
/approve

2021-07-02 14:50 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/operate-first-twitter/pull/23#pullrequestreview-695390970" title="LGTM">harshad16</a>*, *<a href="https://github.com/operate-first/operate-first-twitter/pull/23#pullrequestreview-698263841" title="Approved">oindrillac</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first-twitter).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/operate-first-twitter/blob/main/OWNERS)~~ [oindrillac]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-07-02 15:03 UTC, merged