Bugzilla EDA Tweet
operate-first/operate-first-twitter pull request #25
Opened 2021-07-15 14:00 UTC by aakankshaduggal

2021-07-15 14:00 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **humairak** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @humairak` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first-twitter).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/operate-first-twitter/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["humairak"]} -->

2021-07-15 14:02 UTC, oindrillac requested changes
@aakankshaduggal can you modify this to be under 280 characters?

2021-07-15 14:03 UTC, aakankshaduggal commented
Yes @oindrillac 

On it!

2021-07-15 14:20 UTC, oindrillac requested changes

2021-07-15 14:20 UTC, oindrillac commented on tweets/2021-07/bugzilla.tweet
> +Analyze your CI processes to learn how bugs are impacting your product. Check out https://youtu.be/FMXv3l4NsPc to learn how to fetch bugs linked to failing tests from Red Hat Bugzilla and perform ana
```suggestion
Analyze your CI processes to learn how bugs are impacting your product. Check out https://youtu.be/FMXv3l4NsPc to learn how to fetch bugs linked to failing tests from Red Hat Bugzilla and perform analysis.
```

2021-07-15 14:21 UTC, oindrillac commented
/retest

2021-07-15 14:22 UTC, oindrillac reviewed
/lgtm
/hold

2021-07-15 14:24 UTC, oindrillac commented
/approve
/hold

2021-07-15 14:24 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/operate-first-twitter/pull/25#issuecomment-880738214" title="Approved">oindrillac</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Foperate-first-twitter).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/operate-first-twitter/blob/main/OWNERS)~~ [oindrillac]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-07-19 12:58 UTC, oindrillac commented
/unhold

2021-07-19 12:59 UTC, merged